services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phicargo
    volumes:
      - db_data_phicargo:/var/lib/mysql
    ports:
      - "3308:3306"
    expose:
      - 3306
    restart: always

volumes:
  db_data_phicargo:
  