<?php
$titulo = 'Viaje';
require_once('../../includes2/head2.php');
require_once('../../includes2/footer.php');
require_once('getViaje.php');
require_once('viaje.php');
require_once('../panel_envio/modal/modal.php');
require_once('../../mysql/conexion.php');
require_once('../viaje/cancelar/modal_cancelar.php');
require_once('../correos/ligar_correos/modal_ligar.php');
require_once('checklist/canvas.php');
require_once('../custodia/offcanvas.php');
require_once('../codigos/offcanvas_editar_equipo.php');
require_once('../documentacion/panel/offcanvas.php');
require_once('../alertas/canvas/offcanvas.php');
require_once('../incidencias/canvas.php');
require_once('funciones.php');
require_once('../funciones/funciones.php');
require_once('../funciones/funciones2.php');
